import {useEffect,useMemo,useState} from 'react'
import {LayoutDashboard,ReceiptText,Upload,ChartNoAxesCombined,Tags,Repeat2,SlidersHorizontal,Settings,Search,ArrowUpRight,ArrowDownLeft,WalletCards,RefreshCw,AlertTriangle,CheckCircle2,Menu,X,RotateCcw} from 'lucide-react'
import {api,inr} from './api'

type Page = 'dashboard'|'transactions'|'import'|'analytics'|'categories'|'patterns'|'rules'|'settings'
const nav:[Page,string,any][]=[['dashboard','Dashboard',LayoutDashboard],['transactions','Transactions',ReceiptText],['import','Import',Upload],['analytics','Analytics',ChartNoAxesCombined],['categories','Categories',Tags],['patterns','Patterns',Repeat2],['rules','Rules',SlidersHorizontal],['settings','Settings',Settings]]

function App(){
 const [page,setPage]=useState<Page>('dashboard'); const [mobileMenu,setMobileMenu]=useState(false)
 return <div className="app-shell">
   <aside className={`sidebar ${mobileMenu?'open':''}`}><div className="brand"><div className="logo">₹</div><div><b>PhonePe</b><span>Analyser</span></div></div>
    <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobileMenu(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav>
    <div className="privacy-pill">LOCAL ONLY · NO AI</div>
   </aside>
   {mobileMenu&&<div className="scrim" onClick={()=>setMobileMenu(false)}/>} 
   <main><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMobileMenu(v=>!v)}>{mobileMenu?<X/>:<Menu/>}</button><div><div className="eyebrow">PHONEPE FINANCE</div><b>{nav.find(n=>n[0]===page)?.[1]}</b></div><div className="user-dot">U</div></header>
   <div className="content">{page==='dashboard'?<Dashboard/>:page==='transactions'?<Transactions/>:page==='import'?<Importer/>:page==='analytics'?<Analytics/>:page==='categories'?<Categories/>:page==='patterns'?<Patterns/>:page==='rules'?<Rules/>:<SettingsPage/>}</div></main>
   <div className="bottom-nav">{nav.slice(0,6).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={19}/><span>{label}</span></button>)}</div>
 </div>
}

function useLoad<T>(path:string, initial:T){const [data,setData]=useState<T>(initial); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const reload=()=>{setLoading(true);api<T>(path).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(reload,[path]); return {data,error,loading,reload}}

function Dashboard(){const {data,loading,error,reload}=useLoad<any>('/api/dashboard',{categories:[],top_merchants:[],daily_spending:[]});
 const max=Math.max(1,...data.daily_spending.map((x:any)=>x.amount));
 return <><Title title="Dashboard" subtitle="Overview of your transactions, spending and receipts" action={<button className="ghost" onClick={reload}><RefreshCw size={16}/>Refresh</button>}/>{error&&<ErrorBox text={error}/>}<div className="metric-grid">
 <Metric label="Net spending" value={inr(data.total_spent||0)} icon={<ArrowUpRight/>} tone="red"/><Metric label="Receipts" value={inr(data.total_received||0)} icon={<ArrowDownLeft/>} tone="green"/><Metric label="Net flow" value={inr(data.net_flow||0)} icon={<WalletCards/>} tone={(data.net_flow||0)>=0?'green':'red'}/><Metric label="Transactions" value={String(data.transaction_count||0)} icon={<ReceiptText/>}/></div>
 <div className="grid-2"><section className="panel"><PanelTitle title="Daily spending" sub="Recent transaction days"/><div className="bars">{data.daily_spending.map((x:any)=><div className="bar-wrap" key={x.date} title={`${x.date}: ${inr(x.amount)}`}><div className="bar" style={{height:`${Math.max(4,(x.amount/max)*100)}%`}}/><span>{x.date.slice(8)}</span></div>)}</div></section>
 <section className="panel"><PanelTitle title="Spending by category" sub="Rule-based, editable categories"/><RankList rows={data.categories.map((x:any)=>({name:x.name,value:x.amount}))}/></section></div>
 <section className="panel"><PanelTitle title="Top counterparties" sub="Lifetime debit totals"/><div className="merchant-grid">{data.top_merchants.map((x:any,i:number)=><div className="merchant" key={x.name}><div className="rank">{i+1}</div><div><b>{x.name}</b><span>{x.count} transactions</span></div><strong>{inr(x.amount)}</strong></div>)}</div></section></>}

function Transactions(){const [q,setQ]=useState(''); const [direction,setDirection]=useState(''); const [page,setPage]=useState(1); const path=`/api/transactions?q=${encodeURIComponent(q)}&direction=${direction}&page=${page}&page_size=50`; const {data,loading,error}=useLoad<any>(path,{items:[],total:0});
 return <><Title title="Transactions" subtitle="Search and inspect the normalized PhonePe ledger"/><div className="toolbar panel"><div className="search"><Search size={17}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search merchant, UTR, transaction ID..."/></div><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">All directions</option><option>DEBIT</option><option>CREDIT</option></select><span className="muted">{data.total} results</span></div>{error&&<ErrorBox text={error}/>}<div className="panel table-panel"><table><thead><tr><th>Date</th><th>Description</th><th>Operation</th><th>Category</th><th>Type</th><th className="num">Amount</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id}><td>{new Date(x.datetime).toLocaleDateString('en-IN')}</td><td><b>{x.counterparty||x.description}</b><small>{x.transaction_id}</small></td><td><Badge>{x.operation}</Badge></td><td>{x.category}</td><td><Badge tone={x.direction==='CREDIT'?'green':'red'}>{x.direction}</Badge></td><td className={`num ${x.direction==='CREDIT'?'credit':'debit'}`}>{x.direction==='CREDIT'?'+':'-'}{inr(x.amount)}</td></tr>)}</tbody></table>
 <div className="mobile-tx-list">{data.items.map((x:any)=><div className="mobile-tx" key={x.id}><div className={`tx-icon ${x.direction.toLowerCase()}`}>{x.direction==='CREDIT'?<ArrowDownLeft/>:<ArrowUpRight/>}</div><div className="tx-main"><b>{x.counterparty||x.description}</b><span>{new Date(x.datetime).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {x.category}</span></div><strong className={x.direction==='CREDIT'?'credit':'debit'}>{x.direction==='CREDIT'?'+':'-'}{inr(x.amount)}</strong></div>)}</div></div><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={page*50>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}

function Importer(){const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[status,setStatus]=useState(''),[imports,setImports]=useState<any[]>([]); const load=()=>api<any[]>('/api/imports').then(setImports); useEffect(()=>{load()},[])
 async function previewFile(f:File){setFile(f);setStatus('Reading statement...'); const fd=new FormData();fd.append('file',f); try{const p=await api<any>('/api/imports/preview',{method:'POST',body:fd});setPreview(p);setStatus('')}catch(e:any){setStatus(e.message)}}
 async function commit(){if(!file)return;setStatus('Importing...');const fd=new FormData();fd.append('file',file);try{const r=await api<any>('/api/imports/commit',{method:'POST',body:fd});setStatus(`Imported ${r.new_transactions} new transactions; ${r.duplicates} duplicates skipped.`);load()}catch(e:any){setStatus(e.message)}}
 async function rollback(id:number){if(!confirm('Rollback this import? Imported rows will be hidden, not physically deleted.'))return; await api(`/api/imports/${id}/rollback`,{method:'POST'});load()}
 return <><Title title="Import PhonePe CSV" subtitle="Preview, validate and deduplicate before writing to SQLite"/><section className="panel upload-card"><input id="file" type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&previewFile(e.target.files[0])}/><label htmlFor="file" className="dropzone"><Upload size={34}/><b>{file?file.name:'Choose PhonePe CSV'}</b><span>CSV only · local processing · original IDs stay as text</span></label>{status&&<div className="status-line">{status}</div>}</section>
 {preview&&<section className="panel"><PanelTitle title="Import preview" sub={`${preview.statement_start||'?'} → ${preview.statement_end||'?'}`}/><div className="metric-grid compact"><Mini label="Found" value={preview.transactions_found}/><Mini label="New" value={preview.new_transactions} tone="green"/><Mini label="Already imported" value={preview.already_imported}/><Mini label="Skipped/footer" value={preview.skipped_rows} tone={preview.skipped_rows?'amber':undefined}/></div><div className="preview-totals"><span>Total debits <b>{inr(preview.total_debit_paise/100)}</b></span><span>Total credits <b>{inr(preview.total_credit_paise/100)}</b></span></div>{preview.warnings?.length>0&&<div className="warning"><AlertTriangle/>{preview.warnings[0]}</div>}<div className="actions"><button className="primary" onClick={commit} disabled={preview.new_transactions===0}><CheckCircle2 size={17}/>Import {preview.new_transactions} new transactions</button></div></section>}
 <section className="panel"><PanelTitle title="Import history" sub="Reversible batches"/>{imports.length===0?<Empty text="No imports yet"/>:<div className="history">{imports.map(x=><div className="history-row" key={x.id}><div><b>{x.filename}</b><span>{x.period?.[0]} → {x.period?.[1]} · {x.new} new · {x.duplicates} duplicates</span></div><Badge tone={x.status==='ROLLED_BACK'?'amber':'green'}>{x.status}</Badge>{x.status!=='ROLLED_BACK'&&<button className="icon-btn" title="Rollback" onClick={()=>rollback(x.id)}><RotateCcw size={16}/></button>}</div>)}</div>}</section></>}

function Analytics(){const cats=useLoad<any[]>('/api/analytics/categories',[]);const merchants=useLoad<any[]>('/api/analytics/merchants',[]); return <><Title title="Analytics" subtitle="Deterministic category and counterparty breakdowns"/><div className="grid-2"><section className="panel"><PanelTitle title="Category spending" sub="Debit totals"/><RankList rows={cats.data.map(x=>({name:x.name,value:x.amount,meta:`${x.transactions} tx`}))}/></section><section className="panel"><PanelTitle title="Top counterparties" sub="All directions combined"/><RankList rows={merchants.data.slice(0,15).map(x=>({name:x.name,value:x.total,meta:`${x.transactions} tx · avg ${inr(x.average)}`}))}/></section></div></>}
function Categories(){const {data}=useLoad<any[]>('/api/analytics/categories',[]); return <><Title title="Categories" subtitle="Spend taxonomy generated by deterministic rules"/><div className="category-cards">{data.map((x:any)=><section className="panel category-card" key={x.name}><div className="category-icon"><Tags/></div><div><b>{x.name}</b><span>{x.transactions} transactions</span></div><strong>{inr(x.amount)}</strong></section>)}</div></>}
function Patterns(){const {data,error}=useLoad<any[]>('/api/patterns',[]); return <><Title title="Payment & receipt patterns" subtitle="Recurring and frequent behavior detected from dates and amounts"/>{error&&<ErrorBox text={error}/>}<div className="pattern-grid">{data.map((x:any,i:number)=><section className="panel pattern-card" key={i}><div className="pattern-head"><Badge tone={x.direction==='CREDIT'?'green':'red'}>{x.direction}</Badge><Badge tone={x.status==='CONFIRMED'?'green':'amber'}>{x.status}</Badge></div><h3>{x.counterparty}</h3><div className="pattern-money">{inr(x.median_amount_paise/100)} <small>typical</small></div><div className="pattern-stats"><span><b>{x.occurrences}</b> occurrences</span><span><b>{x.cadence||'Irregular'}</b> cadence</span><span><b>{Math.round(x.amount_stability*100)}%</b> amount stability</span><span><b>{x.next_expected||'—'}</b> next expected</span></div><div className="pattern-type">{x.pattern_type.replaceAll('_',' ')}</div></section>)}</div>{data.length===0&&<Empty text="Import more history to detect recurring or frequent patterns."/>}</>}
function Rules(){const {data}=useLoad<any[]>('/api/rules',[]);return <><Title title="Rule engine" subtitle="Built-in description grammar and deterministic category rules"/><section className="panel table-panel"><table><thead><tr><th>Area</th><th>Priority</th><th>Match</th><th>Pattern</th><th>Result</th><th>Status</th></tr></thead><tbody>{data.map((r:any)=><tr key={r.id}><td><Badge>{r.area}</Badge></td><td>{r.priority}</td><td>{r.match_field} · {r.match_type}</td><td><code>{r.pattern}</code></td><td>{r.operation||r.category||'—'}</td><td><Badge tone={r.enabled?'green':'amber'}>{r.enabled?'Enabled':'Disabled'}</Badge></td></tr>)}</tbody></table></section></>}
function SettingsPage(){return <><Title title="Settings" subtitle="Local-first defaults"/><div className="settings-grid"><section className="panel setting"><b>Privacy</b><p>All transaction processing is local. No AI, embeddings, cloud APIs or telemetry are used.</p><Badge tone="green">LOCAL ONLY</Badge></section><section className="panel setting"><b>Money storage</b><p>Amounts are stored as integer paise. Transaction IDs and UTRs remain text to preserve leading zeroes.</p></section><section className="panel setting"><b>Mobile UI</b><p>Responsive card layouts, horizontal-safe tables, touch targets and a bottom navigation bar are built in.</p></section></div></>}

function Title({title,subtitle,action}:{title:string,subtitle:string,action?:any}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function PanelTitle({title,sub}:{title:string,sub:string}){return <div className="panel-title"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Metric({label,value,icon,tone}:{label:string,value:string,icon:any,tone?:string}){return <section className="metric"><div className={`metric-icon ${tone||''}`}>{icon}</div><span>{label}</span><b>{value}</b></section>}
function Mini({label,value,tone}:{label:string,value:any,tone?:string}){return <div className={`mini ${tone||''}`}><span>{label}</span><b>{value}</b></div>}
function Badge({children,tone}:{children:any,tone?:string}){return <span className={`badge ${tone||''}`}>{children}</span>}
function ErrorBox({text}:{text:string}){return <div className="error"><AlertTriangle/> {text}</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function RankList({rows}:{rows:{name:string,value:number,meta?:string}[]}){const max=Math.max(1,...rows.map(r=>r.value));return <div className="rank-list">{rows.map((r,i)=><div className="rank-row" key={r.name}><div className="rank-label"><span>{r.name}</span>{r.meta&&<small>{r.meta}</small>}</div><div className="progress"><i style={{width:`${(r.value/max)*100}%`}}/></div><b>{inr(r.value)}</b></div>)}</div>}
export default App
